/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: GIYWBY (https://sketchfab.com/GIYWBY)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/raqueta-de-ping-pong-2531d5a1d03f46e0a0dbc5d9fd1e416f
Title: Raqueta de ping pong
*/

import { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { a } from '@react-spring/three'

import RacketScene from '../assets/Racket.glb'

const Racket = (props) => {
  const RacketRef = useRef(null);
  const { nodes, materials } = useGLTF(RacketScene);
  
  return (
    <a.group {...props} dispose={null} >
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_4.geometry}
        material={materials.Madera_paleta}
        position={[0, 9.437, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_6.geometry}
        material={materials.Esponja_paleta}
        position={[0, 10.608, 0.268]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_8.geometry}
        material={materials.Goma_roja}
        position={[0, 10.608, 0.368]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_10.geometry}
        material={materials.Mango_paleta}
        position={[0.001, -0.039, 0.477]}
        rotation={[-Math.PI, 0, -Math.PI]}
        scale={[-1, 1, 1]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_12.geometry}
        material={materials.Mango_paleta}
        position={[0.001, -0.039, -0.477]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_14.geometry}
        material={materials.Esponja_paleta}
        position={[0, 10.608, -0.268]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_16.geometry}
        material={materials.Goma_negra}
        position={[0, 10.608, -0.368]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_18.geometry}
        material={materials.protector_de_goma}
        position={[0, 9.437, 0]}
      />
    </a.group>
  )
}

export default Racket;